package clasesHibernate;
// Generated 7 feb 2025 8:45:58 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Provincias generated by hbm2java
 */
public class Provincias implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private Set alojamientosturismorurals = new HashSet(0);

	public Provincias() {
	}

	public Provincias(String nombre) {
		this.nombre = nombre;
	}

	public Provincias(String nombre, Set alojamientosturismorurals) {
		this.nombre = nombre;
		this.alojamientosturismorurals = alojamientosturismorurals;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getAlojamientosturismorurals() {
		return this.alojamientosturismorurals;
	}

	public void setAlojamientosturismorurals(Set alojamientosturismorurals) {
		this.alojamientosturismorurals = alojamientosturismorurals;
	}

}
